// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/task-cards/DesignA.tsx": () => import("../components/mockups/task-cards/DesignA.tsx"),
  "./components/mockups/task-cards/DesignB.tsx": () => import("../components/mockups/task-cards/DesignB.tsx"),
  "./components/mockups/task-cards/DesignC.tsx": () => import("../components/mockups/task-cards/DesignC.tsx"),
  "./components/mockups/task-cards/DesignD.tsx": () => import("../components/mockups/task-cards/DesignD.tsx"),
  "./components/mockups/task-cards/DesignE.tsx": () => import("../components/mockups/task-cards/DesignE.tsx")
};
