// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clock-24h/Dark.tsx": () => import("../components/mockups/clock-24h/Dark.tsx"),
  "./components/mockups/clock-24h/Minimal.tsx": () => import("../components/mockups/clock-24h/Minimal.tsx"),
  "./components/mockups/flat-cards/FlatA.tsx": () => import("../components/mockups/flat-cards/FlatA.tsx"),
  "./components/mockups/flat-cards/FlatB.tsx": () => import("../components/mockups/flat-cards/FlatB.tsx"),
  "./components/mockups/flat-cards/FlatC.tsx": () => import("../components/mockups/flat-cards/FlatC.tsx"),
  "./components/mockups/flat-cards/FlatD.tsx": () => import("../components/mockups/flat-cards/FlatD.tsx"),
  "./components/mockups/project-view/FolderPills.tsx": () => import("../components/mockups/project-view/FolderPills.tsx"),
  "./components/mockups/project-view/MinimalClean.tsx": () => import("../components/mockups/project-view/MinimalClean.tsx"),
  "./components/mockups/project-view/TreeLines.tsx": () => import("../components/mockups/project-view/TreeLines.tsx"),
  "./components/mockups/sidebar-variants/FolderPills.tsx": () => import("../components/mockups/sidebar-variants/FolderPills.tsx"),
  "./components/mockups/sidebar-variants/MinimalClean.tsx": () => import("../components/mockups/sidebar-variants/MinimalClean.tsx"),
  "./components/mockups/sidebar-variants/TreeLines.tsx": () => import("../components/mockups/sidebar-variants/TreeLines.tsx"),
  "./components/mockups/task-cards/DesignA.tsx": () => import("../components/mockups/task-cards/DesignA.tsx"),
  "./components/mockups/task-cards/DesignB.tsx": () => import("../components/mockups/task-cards/DesignB.tsx"),
  "./components/mockups/task-cards/DesignC.tsx": () => import("../components/mockups/task-cards/DesignC.tsx"),
  "./components/mockups/task-cards/DesignD.tsx": () => import("../components/mockups/task-cards/DesignD.tsx"),
  "./components/mockups/task-cards/DesignE.tsx": () => import("../components/mockups/task-cards/DesignE.tsx")
};
